# Generated by Django 6.0.2 on 2026-02-20 07:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItemAvaliacaoDesempenho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dimensao', models.CharField(choices=[('Comportamento', 'Comportamento'), ('Entregas', 'Entregas'), ('Trabalho em equipe', 'Trab Equipe')], max_length=20)),
                ('tipoItemAvaliacaoDesempenho', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoDesempenho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesCompetencia', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=2)),
                ('statusAvaliacao', models.CharField(choices=[('Criada', 'Criada'), ('Em elaboração', 'Elaboracao'), ('Em avaliação', 'Avaliacao'), ('Concluída', 'Concluida')], default='Criada', max_length=20)),
                ('nota', models.FloatField(default=0)),
                ('sugestoesSupervisor', models.TextField()),
                ('observacoesAvaliado', models.TextField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='core.colaborador')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='core.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAvaliacaoDesempenho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacoes', models.TextField()),
                ('nota', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avaliacaoDesempenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemavaliacaodesempenho', to='core.avaliacaodesempenho')),
                ('tipoItemAvaliacaoDesempenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoitemavaliacaodesempenho')),
            ],
        ),
    ]
