# Generated by Django 6.0.2 on 2026-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='tipo',
            field=models.IntegerField(
                choices=[
                    (1,
                     'Colaborador'),
                    (2,
                     'Supervisor')],
                default=1),
        ),
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='mesCompetencia',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1,
                     'Janeiro'),
                    (2,
                     'Fevereiro'),
                    (3,
                     'Março'),
                    (4,
                     'Abril'),
                    (5,
                     'Maio'),
                    (6,
                     'Junho'),
                    (7,
                     'Julho'),
                    (8,
                     'Agosto'),
                    (9,
                     'setembro'),
                    (10,
                     'Outubro'),
                    (11,
                     'Novembro'),
                    (12,
                     'Dezembro')],
                default=2),
        ),
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='nota',
            field=models.FloatField(
                blank=True,
                default=0),
        ),
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='observacoesAvaliado',
            field=models.TextField(
                blank=True),
        ),
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='statusAvaliacao',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Criada',
                     'Criada'),
                    ('Em elaboração',
                     'Elaboracao'),
                    ('Em avaliação',
                     'Avaliacao'),
                    ('Concluída',
                     'Concluida')],
                default='Criada',
                max_length=20),
        ),
    ]
