# Generated by Django 6.0.2 on 2026-02-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colaborador_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='mesCompetencia',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1,
                     'Janeiro'),
                    (2,
                     'Fevereiro'),
                    (3,
                     'Março'),
                    (4,
                     'Abril'),
                    (5,
                     'Maio'),
                    (6,
                     'Junho'),
                    (7,
                     'Julho'),
                    (8,
                     'Agosto'),
                    (9,
                     'setembro'),
                    (10,
                     'Outubro'),
                    (11,
                     'Novembro'),
                    (12,
                     'Dezembro')]),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaodesempenho',
            unique_together={
                (
                    'colaborador',
                    'mesCompetencia')},
        ),
    ]
