# Generated by Django 6.0.2 on 2026-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_avaliacaodesempenho_mescompetencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador', name='tipo', field=models.IntegerField(
                choices=[
                    (1, 'Colaborador'), (2, 'Supervisor')]), ), ]
