# Generated by Django 6.0.2 on 2026-02-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_colaborador_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador', name='tipo', field=models.IntegerField(
                blank=True, choices=[
                    (1, 'Colaborador'), (2, 'Supervisor')]), ), ]
