# Generated by Django 6.0.2 on 2026-02-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_colaborador_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='statusAvaliacao',
            field=models.CharField(
                choices=[
                    ('Criada',
                     'Criada'),
                    ('Em elaboração',
                     'Elaboracao'),
                    ('Em avaliação',
                     'Avaliacao'),
                    ('Concluída',
                     'Concluida')],
                default='Criada',
                max_length=20),
        ),
    ]
