# Generated by Django 6.0.2 on 2026-02-22 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_mes_competencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaodesempenho',
            old_name='observacoesAvaliado',
            new_name='observacoes_avaliado',
        ),
        migrations.RenameField(
            model_name='avaliacaodesempenho',
            old_name='statusAvaliacao',
            new_name='status_avaliacao',
        ),
        migrations.RenameField(
            model_name='avaliacaodesempenho',
            old_name='sugestoesSupervisor',
            new_name='sugestoes_supervisor',
        ),
        migrations.RenameField(
            model_name='itemavaliacaodesempenho',
            old_name='tipoItemAvaliacaoDesempenho',
            new_name='tipo_item_avaliacao_desempenho',
        ),
        migrations.RenameField(
            model_name='tipoitemavaliacaodesempenho',
            old_name='tipoItemAvaliacaoDesempenho',
            new_name='tipo_item_avaliacao_desempenho',
        ),
        migrations.RemoveField(
            model_name='itemavaliacaodesempenho',
            name='avaliacaoDesempenho',
        ),
        migrations.AddField(
            model_name='itemavaliacaodesempenho',
            name='avaliacao_desempenho',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='item_avaliacao_desempenho',
                to='core.avaliacaodesempenho'),
        ),
    ]
