# Generated by Django 6.0.2 on 2026-02-22 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core',
         '0009_rename_observacoesavaliado_avaliacaodesempenho_observacoes_avaliado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemavaliacaodesempenho',
            name='avaliacao_desempenho',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='item_avaliacao_desempenho',
                to='core.avaliacaodesempenho'),
            preserve_default=False,
        ),
    ]
