# Generated by Django 6.0.2 on 2026-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_itemavaliacaodesempenho_avaliacao_desempenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodesempenho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-02-23 02:54:21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaodesempenho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-02-23 02:54:21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tipoitemavaliacaodesempenho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-02-23 02:54:21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoitemavaliacaodesempenho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
